# Generated by Django 4.1.7 on 2023-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
