# Generated by Django 4.1.6 on 2023-02-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='image',
        ),
        migrations.AddField(
            model_name='inventory',
            name='images',
            field=models.FileField(blank=True, upload_to='inventory_images'),
        ),
    ]
